sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"

before_script:
  - 'if [ -n "${BABEL-}" ]; then make bootstrap-babel ; fi'
  - 'if [ -n "${FLOWTESTS-}" ]; then make bootstrap-flow ; fi'
  - 'BABEL_ENV=test npm run build'

script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -n "${FLOW-}" ]; then npm run flow ; fi'
  - 'if [ -n "${FLOWTESTS-}" ]; then make test-flow ; fi'
  - 'if [ -n "${BABEL-}" ]; then make test-babel ; fi'
  - 'if [ -z "${LINT-}" ] && [ -z "${FLOW-}" ] && [ -z "${BABEL-}" ] && [ -z "${FLOWTESTS-}" ]; then npm run test-ci ; fi'

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true
    - node_js: "node"
      env: FLOW=true
    - node_js: "node"
      env: BABEL=true
    - node_js: "node"
      env: FLOWTESTS=true
  allow_failures:
    - node_js: "node"
      env: FLOWTESTS=true

after_success: 'if [ -z "${LINT-}" ] && [ -z "${FLOW-}" ] && [ -z "${FLOWTESTS-}" ]; then npm run coverage ; fi'

notifications:
  slack: babeljs:5Wy4QX13KVkGy9CnU0rmvgeK
