---
git:
  depth: 1
sudo: false
language: node_js

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"

before_script: make bootstrap-babel

script:
  - npm run test_cov
  - make test-babel

after_success: npm run coverage

notifications:
  slack: babeljs:5Wy4QX13KVkGy9CnU0rmvgeK
